site_name: Achilles C. Macunlay
site_url: https://acmacunlay.github.io/
site_description: Blog and portfolio of Achilles C. Macunlay
site_author: Achilles C. Macunlay

# repo_url: https://github.com/acmacunlay/blog/

nav:
  - Home: index.md
  # - Tags: tags.md
  # - Portfolio: ./portfolio/index.md

# https://squidfunk.github.io/mkdocs-material/creating-your-site/#configuration
theme:
  name: material

  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
  palette:
    scheme: default

  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/
  font:
    text: Roboto
    code: Roboto Mono

  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/
  # icon:
  #   logo: material/book-cog-outline

  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
  features:
    - navigation.footer
    - navigation.instant
    - navigation.sections
    # - navigation.tabs
    - navigation.top
    - navigation.tracking
    # - toc.integrate
    - content.code.copy

# https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/
extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - manage
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/acmacunlay
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/acmacunlay

# https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/
plugins:
  - tags:
      tags_file: tags.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

copyright: Copyright &copy; 2023 Achilles C. Macunlay
