site_name: Achilles Macunlay
site_url: https://achilles.macunlay.com/
site_description: Achilles C. Macunlay
site_author: Achilles C. Macunlay

nav:
  - Home: index.md
  - Tags: tags.md
  - Articles: 
      - blog/index.md

theme:
  name: material
  palette:
    primary: white
  font:
    text: Ubuntu
    code: Ubuntu Mono

  logo: assets/logo.png
  favicon: assets/favicon.png

  features:
    - content.code.annotate
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - content.code.copy
    - search.suggest
    - search.highlight

extra:
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback!
    provider: google
    property: G-CE6N5FR534
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the quality of our articles and whether users
      find what they're searching for. With your consent, you're helping us to
      make our articles better.
    actions:
      - accept
      - manage 
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/acmacunlay
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/acmacunlay

plugins:
  # - glightbox
  - blog:
      blog_dir: blog
      enabled: true
      archive: false
      post_date_format: full
      authors: true
      authors_file: blog/.authors.yml
      categories: true
      categories_name: Categories
      pagination: true
      pagination_per_page: 10
      post_url_format: "{slug}"
  - search
  - tags:
      tags_file: tags.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html

copyright: >-
  Copyright &copy; 2023 Achilles C. Macunlay
  <br>
  <a href="#__consent">Change Cookie Settings</a>
