site_name: Achilles Macunlay
site_url: https://acmacunlay.github.io/

nav:
  - Home: index.md

# https://squidfunk.github.io/mkdocs-material/creating-your-site/#configuration
theme:
  name: material

  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
  palette:
    # Palette toggle for light mode
    - scheme: default
      accent: indigo
      primary: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      accent: indigo
      primary: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/
  font:
    text: Roboto
    code: Roboto Mono

  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/
  icon:
    logo: material/library

  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
  features:
    - navigation.footer
    - navigation.instant
    - navigation.tabs
    - navigation.tracking

# https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/
extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - manage
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/acmacunlay
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/acmacunlay

copyright: >-
  Copyright &copy; 2023 Achilles C. Macunlay
  <br>
  <a href="#__consent">Change Cookie Settings</a>
  <br>
