site_name: Achilles Macunlay
site_url: https://acmacunlay.github.io/
site_description: Blog and portfolio of Achilles C. Macunlay
site_author: Achilles C. Macunlay

nav:
  - Home: index.md
  - Articles: blog/index.md
  # - Tags: tags.md

theme:
  name: material

  palette:
    primary: white

  font:
    text: Fira Sans
    code: Fira Code

  icon:
    logo: material/code-json
  
  favicon: assets/images/favicon.png

  features:
    - content.code.annotate
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - content.code.copy

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/acmacunlay
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/acmacunlay

plugins:
  - blog:
      blog_dir: blog
      enabled: true
      archive: false
      post_date_format: full
      authors: true
      authors_file: blog/.authors.yml
  - tags:
      tags_file: tags.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

copyright: Copyright &copy; 2023 Achilles C. Macunlay
